headerPath = "scripts/license-header.txt"

includes = [
    "*.pkl",
    "*.tmSnippet",
]

[git]
attrs = 'auto'
ignore = 'auto'

[properties]
copyrightOwner = "Apple Inc. and the Pkl project authors"

[mapping.XML_STYLE]
extensions = ["tmSnippet"]
